[project]
name = "python-async-scenarios"
version = "0.1.0"
requires-python = ">=3.11"
dependencies = [
    "aiohttp==3.7.4.post0",
    "aiosqlite==0.17.0",
    "asyncpg==0.27.0",
    "django==3.2.3",
    "psycopg2-binary>=2.9.10",
    "requests==2.25.1",
]
